[package]
name = "libbpf-cargo"
description = "Cargo plugin to build bpf programs"
repository = "https://github.com/libbpf/libbpf-rs"
homepage = "https://github.com/libbpf/libbpf-rs"
documentation = "https://docs.rs/crate/libbpf-cargo"
readme = "README.md"
version = "0.23.2"
authors = ["Daniel Xu <dxu@dxuuu.xyz>", "Daniel Müller <deso@posteo.net>"]
edition = "2021"
rust-version = "1.71"
license = "LGPL-2.1-only OR BSD-2-Clause"
keywords = ["bpf", "ebpf", "libbpf"]

[badges]
maintenance = { status = "actively-developed" }

# Crate is named libbpf-cargo to be consistent with libbpf-rs.
# Binary must be named cargo-${SUBCOMMAND} to interop with cargo.
[[bin]]
name = "cargo-libbpf"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[features]
# By default the crate uses a vendored libbpf, but requires other
# necessary libs to be present on the system.
default = ["libbpf-rs/default"]

[dependencies]
anyhow = "1.0.1"
cargo_metadata = "0.15.0"
libbpf-rs = { version = "0.23", default-features = false, path = "../libbpf-rs" }
memmap2 = "0.5"
num_enum = "0.5"
regex = { version = "1.6.0", default-features = false, features = ["std", "unicode-perl"] }
scroll = "0.11"
scroll_derive = "0.11"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.3"
clap = { version = "4.0.32", features = ["derive"] }

[dev-dependencies]
goblin = "0.6"
vmlinux = { path = "../vmlinux" }
